"""Add cover_url to note

Revision ID: 286c3679d719
Revises: 8e149c4cd1f4
Create Date: 2026-02-28 16:05:55.833328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286c3679d719'
down_revision = '8e149c4cd1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
