"""Add dept_code to notes

Revision ID: 8e149c4cd1f4
Revises: 9ffd7cdcdf29
Create Date: 2026-02-15 13:53:11.157004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef4149c4cd1'
down_revision = '9ffd7cdcdf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_code', sa.String(length=3), nullable=True))
        batch_op.create_index(batch_op.f('ix_note_dept_code'), ['dept_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_dept_code'))
        batch_op.drop_column('dept_code')

    # ### end Alembic commands ###
