"""Add location and start_at to Note

Revision ID: 9ffd7cdcdf29
Revises: 58e77a0862fe
Create Date: 2026-02-07 17:43:27.308570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffd7cdcdf29'
down_revision = '58e77a0862fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('start_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('start_at')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
